all:
	g++ camera_test.cpp -o camera_test -I/usr/local/include/opencv4/ -I/usr/local/include/opencv4/opencv2 -I/usr/local/include/raspicam -L/opt/vc/lib -lraspicam -lraspicam_cv -lmmal -lmmal_core -lmmal_util -lopencv_core -lopencv_highgui -lopencv_videoio -lopencv_imgproc
